# Generated by Django 5.1.7 on 2025-04-06 09:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('iso_code', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('iso3_code', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=10, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='geographic__name_e13bd6_idx'), models.Index(fields=['iso_code'], name='geographic__iso_cod_3dc7f4_idx'), models.Index(fields=['iso3_code'], name='geographic__iso3_co_e45133_idx'), models.Index(fields=['geometry'], name='geographic__geometr_ee0e4b_idx'), models.Index(fields=['centroid'], name='geographic__centroi_686f55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('admin_level', models.PositiveSmallIntegerField(default=1)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geographic_data.country')),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=255)),
                ('timezone', models.CharField(blank=True, max_length=40, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('feature_code', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geographic_data.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='geographic_data.region')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'region', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='geographic__name_bac916_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['code'], name='geographic__code_92a6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['country'], name='geographic__country_14972d_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['admin_level'], name='geographic__admin_l_03ef09_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['geometry'], name='geographic__geometr_96fcee_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['centroid'], name='geographic__centroi_6e806c_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['country', 'name'], name='geographic__country_c9a93e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'name')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='geographic__name_952e19_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name_ascii'], name='geographic__name_as_ddfe6a_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country'], name='geographic__country_adb1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region'], name='geographic__region__0e707b_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['population'], name='geographic__populat_b91323_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['feature_code'], name='geographic__feature_885dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['geometry'], name='geographic__geometr_a5f160_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'region', 'name'], name='geographic__country_cdd3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'population'], name='geographic__country_c4915b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'region', 'name')},
        ),
    ]
