# Generated by Django 5.1.7 on 2025-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('owner', 'Owner'), ('organization', 'Real Estate Organization'), ('developer', 'Developer')], default='guest', max_length=25, verbose_name='User Role'),
        ),
    ]
